<?php

declare(strict_types=1);

namespace Gooyer\ClassFinder\Tests;

use Composer\Autoload\ClassLoader;
use Gooyer\ClassFinder\ApplyFilters;
use Gooyer\ClassFinder\ClassFinder;
use Gooyer\ClassFinder\ClassFinderInterface;
use Gooyer\ClassFinder\Exceptions\NamespaceRequiredException;
use Gooyer\ClassFinder\Filter;

class ClassFinderTest extends \PHPUnit\Framework\TestCase
{
    /**
     * @var ClassLoader
     */
    private $classLoader;


    protected function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        $this->classLoader = require(realpath(__DIR__ . "/../vendor/autoload.php"));
    }

}